### ISSUE TITLE
Feedback for “ Airtable”

### ISSUE THREAD

**Issue by ClemRSYB** [BaseQL/baseql-docs#7]
Hello!

I'd like to report a bug. When querying a column (playlistPool) that hosts items (playlists) that are linked to another table, depending on whether a filter is present or not, some playlists within that pool get a null id field or not.

**Comment by benoror** [comment]
We have a known issue whenever you call a column ID (case-insensitive) it messes up with Airtable's internal id column. We confirmed this has an impact on relationships too. Here's a test we did by renaming it on our People->Cities relation from our [Showcase database](https://docs.baseql.com/playground/airtable):

https://recordit.co/tZTNdlFGIu

As a workaround in the meantime we suggest you rename those columns in order to avoid this issue.
